<?php
/**
 * Blog Data Array
 * Contains all blog post entries for ipu.co.in
 * New entries are prepended by the automation/deploy-blog.py script.
 */

$blogs = [
    ['category' => 'MBA', 'title' => 'MBA Admission in IP University 2026', 'url' => 'mba-admission-ip-university.php', 'img' => 'assets/images/blog-ipu-mba.jpg', 'excerpt' => 'Complete guide to MBA admission at IP University through CAT/CMAT score.', 'read_time' => '7 min'],
    ['category' => 'B.Tech', 'title' => 'IPU B.Tech Admission 2026 – Complete Guide', 'url' => 'IPU-B-Tech-admission-2026.php', 'img' => 'assets/images/IP-University-b-tech-admission.jpg', 'excerpt' => 'JEE Main requirements, counselling process, and top colleges for B.Tech 2026.', 'read_time' => '8 min'],
    ['category' => 'Law', 'title' => 'IPU Law Admission 2026 – CLAT & Counselling Guide', 'url' => 'IPU-Law-Admission-2026.php', 'img' => 'assets/images/IPU-Law-Admission-2025.jpg', 'excerpt' => 'BA LLB and BBA LLB admission through CLAT for IPU 2026.', 'read_time' => '6 min'],
    ['category' => 'Law', 'title' => 'Ultimate Guide to BA LLB Admission in IPU', 'url' => 'ultimate-guide-to-ballb-admission-in-ip-university.php', 'img' => 'assets/images/law.jpg', 'excerpt' => 'Everything about BA LLB 5-year programme at IP University.', 'read_time' => '8 min'],
    ['category' => 'Law', 'title' => 'BBA LLB Admission Guide – IP University', 'url' => 'comprehensive-guide-to-bballb-admission-in-ip-university.php', 'img' => 'assets/images/ipu-bballb.jpg', 'excerpt' => 'Complete guide to BBA LLB admission at IP University.', 'read_time' => '7 min'],
    ['category' => 'BJMC', 'title' => 'Guide to BJMC Colleges Under IP University', 'url' => 'guide-to-bjmc-colleges-under-ip-university.php', 'img' => 'assets/images/IPU-BJMC-Admission.jpg', 'excerpt' => 'Top BJMC colleges, admission process, and placements.', 'read_time' => '5 min'],
    ['category' => 'CET', 'title' => 'IPU CET Exam Date & Admit Card 2026', 'url' => 'ipu-cet-admit-card-exam-date-examination-schedule-and-admit-card.php', 'img' => 'assets/images/ipu-cet-2025-exam-dates-and-admit-card.jpg', 'excerpt' => 'Latest exam schedule and admit card details for IPU CET 2026.', 'read_time' => '4 min'],
    ['category' => 'Economics', 'title' => 'Economics Admission in IP University 2026', 'url' => 'economics-admission-ip-university.php', 'img' => 'assets/images/economics-admission-2025.jpg', 'excerpt' => 'BA Economics admission guide for IP University.', 'read_time' => '5 min'],
    ['category' => 'B.Tech', 'title' => 'GGSIPU Counselling for B.Tech Admission', 'url' => 'GGSIPU-counselling-for-B-Tech-admission.php', 'img' => 'assets/images/ggsipu-counselling.jpg', 'excerpt' => 'Step-by-step counselling process for B.Tech admission.', 'read_time' => '6 min'],
    ['category' => 'Colleges', 'title' => 'Best B.Tech Colleges under IPU – Comparison', 'url' => 'best-btech-colleges-ipu.php', 'img' => 'assets/images/blog-1.jpg', 'excerpt' => 'Compare top engineering colleges under IP University.', 'read_time' => '7 min'],
    ['category' => 'BBA', 'title' => 'Top BBA Colleges Under IP University', 'url' => 'comprehensive-guide-to-bba-colleges-under-ip-university-top-10-institutions.php', 'img' => 'assets/images/comprehensive-guide-to-bba-colleges-under-ip-university-top-10-institutions.jpg', 'excerpt' => 'Top 10 BBA colleges in IP University with placements.', 'read_time' => '6 min'],
    ['category' => 'Admissions', 'title' => 'IPU Admission Guide 2026 – Master Guide', 'url' => 'ipu-admission-guide.php', 'img' => 'assets/images/blog1.jpg', 'excerpt' => 'Complete admission guide for all IPU courses.', 'read_time' => '8 min'],
    ['category' => 'B.Tech', 'title' => 'IPU Choice Filling Strategy 2026', 'url' => 'ipu-choice-filling-strategy.php', 'img' => 'assets/images/blog-4.jpg', 'excerpt' => 'Smart strategies for IPU counselling choice filling.', 'read_time' => '5 min'],
    ['category' => 'BBA', 'title' => 'BBA Admission in IP University', 'url' => 'ipu-bba-admission.php', 'img' => 'assets/images/BBA.jpg', 'excerpt' => 'BBA admission guide with eligibility and colleges.', 'read_time' => '5 min'],
    ['category' => 'Admissions', 'title' => 'Management Quota Admission in IPU', 'url' => 'IP-University-management-quota-admission-eligibility-criteria.php', 'img' => 'assets/images/blog7.jpg', 'excerpt' => 'How management quota works at IP University affiliated colleges.', 'read_time' => '6 min'],
    ['category' => 'B.Tech', 'title' => 'IPU B.Tech Lateral Entry Admission 2026', 'url' => 'ipu-btech-lateral-entry-admission.php', 'img' => 'assets/images/lateral-entry.jpg', 'excerpt' => 'Direct second year B.Tech admission through lateral entry at IPU.', 'read_time' => '5 min'],
    ['category' => 'MBA', 'title' => 'Top MBA Colleges Under IP University', 'url' => 'top-mba-colleges-under-ip-university.php', 'img' => 'assets/images/mba-colleges.jpg', 'excerpt' => 'Ranked list of best MBA colleges affiliated to GGSIPU.', 'read_time' => '7 min'],
    ['category' => 'Admissions', 'title' => 'IPU Online Counselling Process – Step by Step', 'url' => 'ipu-online-counselling-process.php', 'img' => 'assets/images/counselling-process.jpg', 'excerpt' => 'Complete walkthrough of the IPU online counselling registration and process.', 'read_time' => '6 min'],
    ['category' => 'B.Tech', 'title' => 'IPU B.Tech Fee Structure 2026', 'url' => 'ipu-btech-fee-structure.php', 'img' => 'assets/images/fee-structure.jpg', 'excerpt' => 'Detailed fee structure for B.Tech colleges under IP University.', 'read_time' => '4 min'],
    ['category' => 'Admissions', 'title' => 'IPU Admission Through JEE Main 2026', 'url' => 'ipu-admission-through-jee-main.php', 'img' => 'assets/images/jee-main.jpg', 'excerpt' => 'How to get admission in IPU colleges using JEE Main score.', 'read_time' => '6 min'],
    ['category' => 'Colleges', 'title' => 'USICT vs MAIT vs BPIT – IPU College Comparison', 'url' => 'usict-vs-mait-vs-bpit-ipu-comparison.php', 'img' => 'assets/images/college-comparison.jpg', 'excerpt' => 'Head-to-head comparison of top IPU engineering colleges.', 'read_time' => '8 min'],
    ['category' => 'Law', 'title' => 'IPU LLM Admission 2026 – Eligibility & Process', 'url' => 'ipu-llm-admission.php', 'img' => 'assets/images/llm-admission.jpg', 'excerpt' => 'Complete guide to LLM admission at IP University law schools.', 'read_time' => '5 min'],
    ['category' => 'BBA', 'title' => 'IPU BBA Fee Structure & Placement Details', 'url' => 'ipu-bba-fee-structure-placement.php', 'img' => 'assets/images/bba-placement.jpg', 'excerpt' => 'Fee details and placement statistics for BBA at IPU colleges.', 'read_time' => '5 min'],
    ['category' => 'CET', 'title' => 'IPU CET Syllabus 2026 – All Codes', 'url' => 'ipu-cet-syllabus.php', 'img' => 'assets/images/cet-syllabus.jpg', 'excerpt' => 'Complete syllabus for all IPU CET exam codes.', 'read_time' => '6 min'],
    ['category' => 'Admissions', 'title' => 'Documents Required for IPU Admission 2026', 'url' => 'documents-required-ipu-admission.php', 'img' => 'assets/images/documents.jpg', 'excerpt' => 'Checklist of all documents needed for IPU counselling and admission.', 'read_time' => '4 min'],
    ['category' => 'Colleges', 'title' => 'IPU Affiliated Colleges – Complete List 2026', 'url' => 'ipu-affiliated-colleges-complete-list.php', 'img' => 'assets/images/affiliated-colleges.jpg', 'excerpt' => 'Full list of all colleges affiliated to IP University with courses offered.', 'read_time' => '7 min'],
    ['category' => 'B.Tech', 'title' => 'IPU B.Tech Cutoff 2025 – Round-wise Analysis', 'url' => 'ipu-btech-cutoff-analysis.php', 'img' => 'assets/images/cutoff-analysis.jpg', 'excerpt' => 'Round-wise JEE Main cutoff analysis for IPU B.Tech colleges.', 'read_time' => '6 min'],
];
?>
